version: 2

jobs:
  'node-latest':
    docker:
      - image: circleci/node:latest
    working_directory: ~/typescript-starter
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn test

workflows:
  version: 2
  build:
    jobs:
      - 'node-latest'
